---
title: "Использование исключений (Руководство по программированию на C#) | Microsoft Docs"
ms.custom: ""
ms.date: "11/24/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-csharp"
ms.tgt_pltfrm: ""
ms.topic: "article"
dev_langs: 
  - "CSharp"
helpviewer_keywords: 
  - "обработка исключений [C#], об обработке исключений"
  - "исключения [C#], об исключениях"
ms.assetid: 71472c62-320a-470a-97d2-67995180389d
caps.latest.revision: 15
caps.handback.revision: 15
author: "BillWagner"
ms.author: "wiwagn"
manager: "wpickett"
translationtype: Human Translation
---
# Использование исключений (Руководство по программированию на C#)
[!INCLUDE[vs2017banner](../../../csharp/includes/vs2017banner.md)]

В языке C\# ошибки в программе во время выполнения передаются через программу посредством механизма, называемого исключениями.  Исключения создаются кодом, который встречает ошибку и перехватываются кодом, который может исправить ее.  Исключения могут создаваться средой CLR платформы .NET Framework или кодом в программе.  В случае исключения, оно передается по стеку вызовов пока не будет найден оператор `catch` для исключения.  Не перехваченные исключения обрабатываются универсальным обработчиком исключений, предоставляемым системой, который открывает диалоговое окно.  
  
 Исключения представляются посредством классов, производных от <xref:System.Exception>.  Такой класс устанавливает тип исключения и содержит свойства с подробными сведениями об исключении.  При генерации исключения создается экземпляр класса, производного от исключения, настраиваются свойства исключения \(необязательно\), а затем при помощи ключевого слова `throw` создается объект.  Примеры.  
  
 [!CODE [csProgGuideExceptions#1](../CodeSnippet/VS_Snippets_VBCSharp/csProgGuideExceptions#1)]  
  
 После генерации исключения среда выполнения проверяет текущий оператор и устанавливает, находится ли он в блоке `try`.  Все блоки `catch` \(если они имеются\), связанные с блоком `try`, проверяются на возможность обработать исключение.  В блоках `Catch` обычно задаются типы исключений; если тип блока `catch` совпадает с типом исключения или базовым классом исключения, то блок `catch` может обработать данный метод.  Примеры.  
  
 [!CODE [csProgGuideExceptions#2](../CodeSnippet/VS_Snippets_VBCSharp/csProgGuideExceptions#2)]  
  
 Если оператор, создающий исключение, расположен вне блока `try` или если блок `try`, в котором он расположен, не имеет соответствующего блока `catch`, среда выполнения проверяет вызывающий метод на наличие оператора `try` и блоков `catch`.  Время выполнения продолжается до вызывающего стека в поисках совместимого блока `catch`.  После того, как блок `catch` найден и выполнен, управление передается следующему оператору после того блока `catch`.  
  
 Оператор `try` может содержать несколько блоков `catch`.  Выполняется первый оператор `catch`, который может обработать исключение; все последующие операторы `catch`, даже если они совместимы – пропускаются.  Поэтому необходимо, чтобы блоки catch всегда были упорядочены в порядке от более конкретных \(или замыкающих цепочку наследования\) к более общим.  Примеры.  
  
 [!CODE [csProgGuideExceptions#3](../CodeSnippet/VS_Snippets_VBCSharp/csProgGuideExceptions#3)]  
  
 Перед выполнением блока `catch` среда выполнения проверяет наличие блоков `finally`.  Блоки `Finally` позволяют программисту очищать любое неоднозначное состояние, которое могло быть оставлено прерванным блоком `try`, или освобождать любые внешние ресурсы \(например, обработчики графики, подключения к базам данных или потоки файлов\), не дожидаясь сборки мусора во время выполнения для завершения объектов.  Примеры.  
  
 [!CODE [csProgGuideExceptions#4](../CodeSnippet/VS_Snippets_VBCSharp/csProgGuideExceptions#4)]  
  
 Если `WriteByte()` сгенерировал исключение, код во втором блоке `try`, пытающийся повторно открыть файл, не будет выполнен, если `file.Close()` не вызван, и файл останется заблокированным.  Так как блоки `finally` выполняются даже в случае генерации исключения, блок `finally` в предыдущем примере предусматривает правильное закрытие файла и помогает избежать ошибок.  
  
 Если в стеке вызовов после генерации исключения не удается найти совместимый блок `catch`, то происходит одно из трех действий.  
  
-   Если исключение возникло внутри деструктора, деструктор прерывается и вызывается базовый деструктор, если он имеется.  
  
-   Если в стеке вызовов содержится статический конструктор или статический инициализатор поля, генерируется <xref:System.TypeInitializationException> и исходное исключение присваивается свойству <xref:System.Exception.InnerException%2A> нового исключения.  
  
-   По достижении начала потока он прерывается.  
  
## См. также  
 [Руководство по программированию на C\#](../../../csharp/programming-guide/index.md)   
 [Исключения и обработка исключений](../../../csharp/programming-guide/exceptions/exceptions-and-exception-handling.md)